apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescale:5432
    database: $POSTGRES_DB
    user: $POSTGRES_DATA_VIS_USER
    isDefault: true
    editable: true
    secureJsonData:
      password: $POSTGRES_DATA_VIS_PASSWORD
    jsonData:
      sslmode: 'disable'
      timescaledb: true
      postgresVersion: 1000
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400